branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/changelog"
    - changelogFile: "docs/CHANGELOG.md"
  - "@semantic-release/git"
    - assets:
      - "docs/CHANGELOG.md"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - "@semantic-release/release-notes-generator"


