name: "🚀 publish"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  quality:
      name: 🧪 test
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          node-version: [12.x, 14.x, 16.x]
          os: [ ubuntu-latest, windows-latest ]
      
      steps: 
        - name: 📚 checkout
          uses: actions/checkout@v3
        - name: 🟢 node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npm test
      
  publish:
      name: 🚀 publish
      runs-on: ubuntu-latest
      if: ${{ github.ref == 'refs/heads/main' }}
      needs: [ quality ]
      steps:
        - name: 📚 checkout
          uses: actions/checkout@v3
        - name: 🟢 node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - name: 🚀 publish
        - run: npm run semantic-release
          env: 
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
        
