name: "🧪 Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: 🧪 Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout code 📚
        uses: actions/checkout@v3

      - name: Set up Node 🟢
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages ⚙️
        run: npm ci

      - name: Run tests 🧪
        run: npm run test